### ISSUE TITLE
Current nightly does nothing

### ISSUE THREAD

**Issue by daemonspudguy** [AEAEAEAE4343/SimpleClassicThemeTaskbar#1]
I have tried the current nightly on your WinClassic post and it just instantly crashes. No pop-up, just disappears from Task Manager. What's going on?

**Comment by AEAEAEAE4343** [comment]
Make sure you got .NET 4.8 and VC++ 2015 installed.

Sent from my iPhone

On 26 Feb 2020, at 03:03, daemonspudguy <notifications@github.com> wrote:

﻿

I have tried the current nightly on your WinClassic post and it just instantly crashes. No pop-up, just disappears from Task Manager. What's going on?

**Comment by AEAEAEAE4343** [comment]
Is the issue resolved? If so, I'll close it

**Comment by daemonspudguy** [comment]
Ok

**Comment by daemonspudguy** [comment]
I installed .NET 4.8 and it still does nothing

**Comment by AEAEAEAE4343** [comment]
What about visual c++ redist (64 bit)?

Sent from my iPhone

On 29 Feb 2020, at 02:51, daemonspudguy <notifications@github.com> wrote:

﻿

Reopened #1<https://github.com/AEAEAEAE4343/SimpleClassicThemeTaskbar/issues/1>.

**Comment by daemonspudguy** [comment]
Installed

AEAEAEAE4343 <notifications@github.com> schrieb am Sa., 29. Feb. 2020,
05:07:

> What about visual c++ redist (64 bit)?
>
> Sent from my iPhone
>

**Comment by daemonspudguy** [comment]
I'm on LTSC 2019, does the taskbar work on that?

**Comment by AEAEAEAE4343** [comment]
It should work on ANY version of Windows based on Windows 10

**Comment by daemonspudguy** [comment]
I have the x64 versions of VCREDIST 2019 and the latest release of .NET Framework.

**Comment by AEAEAEAE4343** [comment]
Odd, does Windows say the program stopped working or does nothing happen when running the program? Have you tried running with elevation?

Sent from my iPhone

On 29 Feb 2020, at 21:32, daemonspudguy <notifications@github.com> wrote:

﻿

I have the x64 versions of VCREDIST 2019 and the latest release of .NET Framework.

**Comment by daemonspudguy** [comment]
No. Yes I have

AEAEAEAE4343 <notifications@github.com> schrieb am So., 1. März 2020, 05:52:

> Odd, does Windows say the program stopped working or does nothing happen
> when running the program? Have you tried running with elevation?
>
> Sent from my iPhone
>

**Comment by AEAEAEAE4343** [comment]
Then it's probably one of the icons it doens't like. I can't help you without you installing VS 2019 with C++ and debugging the code yourself. I will soon make crash reports a thing.

**Comment by AEAEAEAE4343** [comment]
Closed because of inactivity
