### ISSUE TITLE
Not enough space between Start button and first Taskbar button

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#11]
Windows 10 Pro 2004 x64 / SCT 1.2.2.0 / SCTT 0.0.7712.2869

Using Custom button:
![XP Classic (Bigger) (SCTT)](https://user-images.githubusercontent.com/8242464/107677172-fd2dca80-6c67-11eb-87ed-9ab83e0e39b2.png)

The leftmost taskbar button is too close to the start button:
![space](https://user-images.githubusercontent.com/8242464/107677540-61508e80-6c68-11eb-9e3d-bc301e15b7c0.png)

This seems to happen after changing "Space between taskbar programs", even after changing it to the default setting of 2. If I change it it looks like this after clicking OK:
![space2](https://user-images.githubusercontent.com/8242464/107678023-e20f8a80-6c68-11eb-990c-63253c369356.png)

But clicking then minimizing the first program on the taskbar (next to the Start button) will result in the former image, where it appears to overlap.

For comparison here is the Windows 7 classic taskbar using Classic Shell:
![ClassicShell](https://user-images.githubusercontent.com/8242464/107678373-4fbbb680-6c69-11eb-9b30-03a497279340.png)

And here is Windows XP:
![XP](https://user-images.githubusercontent.com/8242464/107680015-4f241f80-6c6b-11eb-94f0-cea9f33eb043.png)

It's clear there should be more space between the Start button and the first taskbar button. But I'm not sure if SCTT should be doing this, or if I should be adding transparent pixels to the right of the custom Start button PNG image.

**Comment by AEAEAEAE4343** [comment]
Correct. Anything above 55px seems to overlap with other controls.

**Comment by BlohoJo** [comment]
I tried adding transparent pixels... increase width by 4, adding 4 transparent pixels to the right to the right of the custom start button PNG image, but it had no effect.

![XP Classic (Bigger) (SCTT2)](https://user-images.githubusercontent.com/8242464/107681106-a4acfc00-6c6c-11eb-8248-edb7d244d4d3.png)

**Comment by AEAEAEAE4343** [comment]
Correct, it draws the image over the default button background. It's just a math issue

**Comment by AEAEAEAE4343** [comment]
Fix issue speedrun 
Time: 15:03
