### ISSUE TITLE
When closing the SCT box, my Documents folder is displayed

### ISSUE THREAD

**Issue by larryedwards** [AEAEAEAE4343/SimpleClassicThemeTaskbar#13]
After I run SCT and close its box, Explorer is loaded and my Documents folder gets displayed. 

Mostly an annoyance since I then have to close Explorer (I use a different file manager and never use the Documents folder). But something it would be good to fix if you get a chance.

**Comment by AEAEAEAE4343** [comment]
I can't seem to reproduce your issue. Can you give me some or info on the details?

Btw, this is the wrong repository. This one is just for the taskbar.

**Comment by larryedwards** [comment]
Thanks for your reply.

   Here is the sequence of what happens, with a couple of screen
shots. And problem is repeatable (it occurs every time).

1.  I run SCT, it appears as normal on screen, and I click Enable.

2.  SCT goes through its enabling routine (loading CMD, Settings,
etc.). 

3   When that routine completes, Windows FileExplorer loads, and
always to the Documents folder. See first screenshot. (Note that I
never use FileExplorer, nor do I ever use the Documents folder.)

4.  When I close FileExplorer, focus returns to SCT, with its title
bar at first indicating non-selected (second screenshot), and then
after a moment it again becomes the selected process.

   This behavior started after I updated SCT to the new version a week
or so ago. It could also be related to recent updates to Win10 1909
that occurred at about that time (or both in combination).

-- Larry

===== Orig. Msg. =====

**Comment by AEAEAEAE4343** [comment]
Closed: Created an issue on the correct repository:
https://github.com/AEAEAEAE4343/SimpleClassicTheme/issues/29
