### ISSUE TITLE
Quick Launch crunches 32px Icons

### ISSUE THREAD

**Issue by Hayafumi** [AEAEAEAE4343/SimpleClassicThemeTaskbar#2]
Quick Launch doesn't use 16px icons and crunches down 32px icons.
![SCT Quicklaunch](https://user-images.githubusercontent.com/72291868/95129902-9116e500-0710-11eb-9c55-06f3c34db52a.png)

**Comment by AEAEAEAE4343** [comment]
I'm not sure if I've fixed this.

**Comment by AEAEAEAE4343** [comment]
I did, closing this issue
