### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Craftplacer** [AEAEAEAE4343/SimpleClassicThemeTaskbar#20]
- [x] Listen for messages of windows getting created/destroyed
- [x] ~~Reduce CPU usage of 'WindowIsOnCurrentDesktop(hWnd)'~~ This function is now rarely called and has actually been optimized as far as it can.
- [x] Look into repeating changing workspace area (glitching maximized windows)

**Comment by BlohoJo** [comment]
I tried the development build and it crashed immediately. (Clicking "enable" in SCT.)

It appears to be missing a file called `SimpleClassicThemeTaskbar.CodeBridge`

```
Faulting application name: SimpleClassicThemeTaskbar.exe, version: 0.0.7804.42771, time stamp: 0x60513887
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0xd98
Faulting application start time: 0x01d74920205c0c5f
Faulting application path: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6acac671-d915-4575-be43-b72a380ba969
Faulting package full name: 
Faulting package-relative application ID:
```

```
Application: SimpleClassicThemeTaskbar.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at SimpleClassicThemeTaskbar.ApplicationEntryPoint.Main(String[] args)
```

**Comment by Craftplacer** [comment]
> 
> 
> I tried the development build and it crashed immediately. (Clicking "enable" in SCT.)
> 
> It appears to be missing a file called `SimpleClassicThemeTaskbar.CodeBridge`
> 
> ```
> Faulting application name: SimpleClassicThemeTaskbar.exe, version: 0.0.7804.42771, time stamp: 0x60513887
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
> Exception code: 0xe0434352
> Fault offset: 0x0000000000023e49
> Faulting process id: 0xd98
> Faulting application start time: 0x01d74920205c0c5f
> Faulting application path: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 6acac671-d915-4575-be43-b72a380ba969
> Faulting package full name: 
> Faulting package-relative application ID:
> ```
> 
> ```
> Application: SimpleClassicThemeTaskbar.exe
> CoreCLR Version: 5.0.521.16609
> .NET Version: 5.0.5
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> File name: 'SimpleClassicThemeTaskbar.CodeBridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
>    at SimpleClassicThemeTaskbar.ApplicationEntryPoint.Main(String[] args)
> ```

@BlohoJo I moved your comment to another issue as it is unrelated to this one.

**Comment by Craftplacer** [comment]
Seems like it, one thing that's still odd is that Debug.WriteLine blocks execution of the app. (Maybe track that inside another issue?)

**Comment by AEAEAEAE4343** [comment]
I've made it so that Debug.WriteLine is only called when debugging is enabled in the control panel.

**Comment by Craftplacer** [comment]
Of course, but it doesn't fix the underlying issue. I'll close this issue for now though.
