### ISSUE TITLE
"This version of SCTT is part of the SCT Private Alpha. Please use the latest public build instead."

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#3]
When I try to run SimpleClassicThemeTaskbar.exe (latest release, Alpha 0.0.7634.39748), I get the following:

![error01](https://user-images.githubusercontent.com/8242464/100491590-d513de00-30f2-11eb-8a23-02f23130bcc0.png)

![error02](https://user-images.githubusercontent.com/8242464/100491591-d5ac7480-30f2-11eb-8a74-85e0058bf3aa.png)

Anyone else? What am I doing wrong?

**Comment by AEAEAEAE4343** [comment]
Well, SCTT is currently not public. As the dialog box states, it is part of the SCT Private Alpha. The latest public release is available on the WinClassic forum:

https://winclassic.boards.net/thread/740/simple-classic-taskbar-download-link

Sent from my iPhone

On 28 Nov 2020, at 02:55, BlohoJo <notifications@github.com> wrote:

﻿

When I try to run SimpleClassicThemeTaskbar.exe (latest release, Alpha 0.0.7634.39748), I get the following:

[error01]<https://user-images.githubusercontent.com/8242464/100491590-d513de00-30f2-11eb-8a23-02f23130bcc0.png>

[error02]<https://user-images.githubusercontent.com/8242464/100491591-d5ac7480-30f2-11eb-8a74-85e0058bf3aa.png>

Anyone else? What am I doing wrong?

**Comment by BlohoJo** [comment]
Oh, I see, SCTT = Simple Classic Theme Taskbar. Duh!

Please, make it public! I live for these types of programs. :blush:

Or, tell me how to (please?) get access to the private beta! :grin:
