### ISSUE TITLE
No English configuration window?

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#5]
Right click taskbar, "Configure SCT Taskbar".

I see:

![configure](https://user-images.githubusercontent.com/8242464/107286978-4e9f4500-6a2f-11eb-9e1f-1199316a298d.png)

Any way to get this in English?

**Comment by AEAEAEAE4343** [comment]
Bug, please ignore.

**Comment by AEAEAEAE4343** [comment]
Fixed in 7f711bf
