### ISSUE TITLE
Closing the taskbar crashes the taskbar because of an ObjectDisposedException

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#6]
Right click taskbar, select "Configure SCT Taskbar", get this window (don't know how to get this in English; I made a separate issue):

![config_ok](https://user-images.githubusercontent.com/8242464/107287677-4693d500-6a30-11eb-9b82-e7523c72044b.png)

Click OK without touching anything, and SCTT crashes:

![crash](https://user-images.githubusercontent.com/8242464/107287714-54495a80-6a30-11eb-9df7-f5ad79098644.png)

There is no taskbar at all after the crash (no system taskbar, no SCTT taskbar). I can get to the Start Menu by hitting the "Windows" key on the keyboard.

Not sure if there's any kind of log file saved anywhere. But there are two Windows Application Event logs; not sure if they tell you anything useful:

![event_log](https://user-images.githubusercontent.com/8242464/107288311-40eabf00-6a31-11eb-89d8-f3ce7bd20f23.png)

Event 1000, Application Error:
```
Faulting application name: SimpleClassicThemeTaskbar.exe, version: 0.0.7709.39241, time stamp: 0x5fbf100e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x14fc
Faulting application start time: 0x01d6fe65b5e4baed
Faulting application path: C:\SCT\Taskbar\SimpleClassicThemeTaskbar.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 124e0eab-94b4-403f-ac5e-9a80db5057d1
Faulting package full name: 
Faulting package-relative application ID: 
```

Event 1026, .NET Runtime:
```
Application: SimpleClassicThemeTaskbar.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Taskbar'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SimpleClassicThemeTaskbar.Taskbar.BackgroundThreadFunction()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by BlohoJo** [comment]
This crash also happens when right clicking the taskbar and selecting "Exit SCT Taskbar". In that case, SCT Taskbar exits and leaves a system taskbar with no labels on the buttons. But the above crash box and Windows Events still happen.

**Comment by AEAEAEAE4343** [comment]
Thank you! I have noted it.
