### ISSUE TITLE
Classic Context Menu needs reimplementing

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#7]
In SCTT Alpha 0.0.7642.30810, [Taskbar-Context-Menu-Tweaker](https://github.com/rikka0w0/Taskbar-Context-Menu-Tweaker) worked for creating a classic grey Taskbar context menu. 

![sctt_alpha](https://user-images.githubusercontent.com/8242464/107291376-15b69e80-6a36-11eb-80b1-3557669cb78f.png)

In SCTT Beta 0.0.7709.39241, it no longer works:

![sctt_beta](https://user-images.githubusercontent.com/8242464/107291400-1fd89d00-6a36-11eb-9e5f-67e6b9d50fc2.png)

Troubleshooting:

- Ensure C:\Windows\System32\TaskbarContextMenuTweaker.dll is present

- Kill and restart all explorer.exe processes after enabling SCT

- Run `rundll32 TaskbarContextMenuTweaker.dll,Inject`

Didn't work... is it possible to get Taskbar-Context-Menu-Tweaker functionality restored? (Obviously not a huge problem but still something that would be nice if it could still work!) :)

**Comment by AEAEAEAE4343** [comment]
TaskbarContextMenuTweaker had nothing to do with SCTT in the first place. This is because .NET 5 has no easy way for me to create a classic context menu, so I quickly just added in this as a placeholder. Will be addressed.
