### ISSUE TITLE
Request: Time display in 12 or 24 hour format

### ISSUE THREAD

**Issue by BlohoJo** [AEAEAEAE4343/SimpleClassicThemeTaskbar#8]
In SCTT Alpha 0.0.7642.30810, time was displayed in 12 hour format (i.e., 3:00 PM). In the latest Beta 0.0.7709.39241, it's now in 24 hour format (i.e., 15:00).

Personally I prefer 12 hour, but I'm sure others prefer 24... is it possible to make a 12/24 hour option available in the Configuration window?

**Comment by AEAEAEAE4343** [comment]
Belongs to #5 
When .NET changes the languages it also changes the date/time formatting to correspond to local standards
